name: weather_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter: 
    sdk: flutter
  flutter_native_splash: ^2.3.9
  dio: ^5.4.0
  fl_chart: ^0.66.0
  intl: ^0.19.0
  lottie: ^3.0.0
  http: ^1.2.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
  - assets/
  - assets/icons/
  - assets/lotties/

uses-material-design: true


